import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "../components/TopNav";
import "@uploadthing/react/styles.css";
import React from "react";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "NEW T3",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="dark:bg-background dark:text-foreground l bg-black text-white">
          <div className="grid-row-[auto,1fr] grid h-screen">
            <TopNav />
            <main className="no-scrollbar overflow-y-scroll">
              {children}

              <Toaster />
            </main>
          </div>
          {modal}
          <div id="modal-root" />
        </body>
      </html>
    </ClerkProvider>
  );
}
